FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN  pip install mysqlclient

RUN pip install -r requirements.txt

CMD ["python","app.py"]
