services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
      #environment:
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: wordpress
      #MYSQL_USER: wordpress
      #MYSQL_PASSWORD: wordpress
    env_file:
      - path: ./mysql.env

    ports:
      - 3306:3306
    volumes:
      - db-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wp-net
  wordpress:
    image: wordpress:latest
    container_name: wp-wordpress
    depends_on:
      db-mysql:
        condition: service_healthy
          #environment:
          #WORDPRESS_DB_HOST: mysql:3306
          #WORDPRESS_DB_USER: wordpress
          #WORDPRESS_DB_PASSWORD: wordpress
          #WORDPRESS_DB_NAME: wordpress
    env_file:
      - path: ./wp.env
    restart: always
    ports:
      - 8080:80
    volumes:
      - wp-data:/var/www/html
    networks:
      - wp-net

volumes:
    db-mysql:
    wp-data:

networks:
    wp-net:
      driver: bridge
