FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine AS runner

WORKDIR /app

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx","-g","daemon off;"]
